# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c0cd66c6b2811e1015ad0d3a736a35dbdcd448d46bcf629ffb1f3a51238651d2b3119fc3dfff4eadc7fe7c81614b19d0f63cab3efe621cd4b402cef195a023

test:
  secret_key_base: 8dfd7d46b5ecad5428c2292744899a306f0d907c0bc6e5ecb5b5a9d1786911e209806e9373b71cd76a23ae7a89edf10f5eca8b8cad07cab13a3a0dd7c7b64a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
